name: notes_app
description: "A new Flutter project."

# Empêche la publication accidentelle sur pub.dev
publish_to: 'none'

# Version de l’application
version: 1.0.0+1

# Version SDK de Dart/Flutter
environment:
  sdk: ^3.9.2

# Dépendances principales
dependencies:
  flutter:
    sdk: flutter

  # Icônes de style iOS
  cupertino_icons: ^1.0.8

  # Gestion des variables d’environnement (.env)
  flutter_dotenv: ^6.0.0

  # SDK Appwrite
  appwrite: ^8.3.0

# Dépendances de développement
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Règles de linting recommandées
  flutter_lints: ^5.0.0

# Configuration spécifique à Flutter
flutter:
  uses-material-design: true

  # Inclusion du fichier .env dans les assets
  assets:
    - .env
